Story 23465
XITRIX/Phonebook pull request #3
Opened 2018-12-06 11:22 UTC by XITRIX

2018-12-06 11:44 UTC, pocheshire requested changes

2018-12-06 11:44 UTC, pocheshire commented on src/Core/ViewModels/Contacts/ContactsViewModel.cs
> +        public IMvxAsyncCommand<ContactItemVm> NavigateToDetailsCommand => _navigateToDetailsCommand ?? (_navigateToDetailsCommand = new MvxAsyncCommand<ContactItemVm>(item => { return _navigationSer
> `item => { return _navigationService.Navigate<ContactDetailsViewModel, ContactItemVm>(item);`

вынести в отдельный метод

2018-12-06 11:44 UTC, pocheshire commented on src/Core/ViewModels/Contacts/ContactsViewModel.cs
> +                    //TODO:
> `//TODO`

реализовать обработку этой ситуации

2018-12-06 11:44 UTC, pocheshire commented on src/Core/ViewModels/Contacts/ContactsViewModel.cs
> +        }
> `public override void ViewAppeared()`
проверить, как отрабатывает при переходе назад. Возможно нужно перенести в `ViewCreated()`

2018-12-06 11:44 UTC, pocheshire commented on src/Core/ViewModels/Contacts/Items/ContactItemVm.cs
> +        public string PhotoPath => model.Picture.Large;
> `public string PhotoPath => model.Picture.Large;`

Зачем `Large`, если это маленькая иконка в списке? Сэкономь трафик пользователя, поменяй на более маленькую фотку

2018-12-06 14:01 UTC, XITRIX commented on src/Core/ViewModels/Contacts/ContactsViewModel.cs
> +        }
На Андроиде он повторно не вызывается из-за того что по сути и не пропадает, на iOS вызывается при возврате
Переделал

2018-12-06 14:06 UTC, pocheshire commented on src/Core/ViewModels/Contacts/ContactsViewModel.cs
> +        public IMvxAsyncCommand<ContactItemVm> NavigateToDetailsCommand => _navigateToDetailsCommand ?? (_navigateToDetailsCommand = new MvxAsyncCommand<ContactItemVm>(item => { return _navigationSer
И передаёшь ты не item, а item.Model. потому что вьюмоделька не используется как параметр навигации.

2018-12-06 14:17 UTC, pocheshire requested changes

2018-12-06 14:17 UTC, pocheshire commented on src/Core/ViewModels/Contacts/ContactsViewModel.cs
> +                    throw new ArgumentException("Result can not be empty");
Мы уже говорили с тобой про эксепшены внутри VM. У тебя приложение упадёт. Отобрази пользователю диалог с сообщением.

2018-12-06 14:20 UTC, pocheshire requested changes

2018-12-06 14:20 UTC, pocheshire commented on src/Core/ViewModels/Contacts/ContactsViewModel.cs
> +            return _navigationService.Navigate<ContactDetailsViewModel, ContactItemVm>(item);
Передаёшь в навигацию не item, а модель контакта

2018-12-06 14:29 UTC, XITRIX commented on src/Core/ViewModels/Contacts/ContactsViewModel.cs
> +                    throw new ArgumentException("Result can not be empty");
Ну упасть то не упадёт, ниже catch, но ок, сделаю диалог

2018-12-06 14:59 UTC, pocheshire commented on src/Core/ViewModels/Contacts/ContactsViewModel.cs
> +                    throw new ArgumentException("Result can not be empty");
throw можно было бы сделать, если б тебе нужно было перекинуть исключение на другой уровень логики. А так ты вызываешь дорогостоящую операцию лишь для своего удобства, тогда как пользователю все ещё не ясно, что у него произошло

2018-12-07 07:43 UTC, pocheshire approved these changes

2018-12-07 07:43 UTC, merged